### ISSUE TITLE
Gita hub airdrop

### ISSUE THREAD

**Issue by Ak565656** [element-fi/elf-council-frontend#1018]
A great project,
Many powerful project management,
And the project is too big,
I hope there will be good profit from this project

😍❣️
Gitahub id: 0x22075f3cf77c456b2fa7866544dc116830cc01ab9f69431e9ebcfedf70651a14

**Comment by Fabunmiegbe** [comment]
0x27db6595d8af7f2a43b13dd9a9fa1e4f8d73ed88ac06e7cce69c0f0a0b27c537
