### ISSUE TITLE
0x0eb45a5a25a356f3516346d4a839fc96b6526443bac83f0c6d50f5487c6cbe7e

### ISSUE THREAD

**Issue by Akorede00** [element-fi/elf-council-frontend#1020]
0x0eb45a5a25a356f3516346d4a839fc96b6526443bac83f0c6d50f5487c6cbe7e

**Comment by elbaratonr** [comment]
0x203e3f57f4f2a0d1f6d7b700ed93e68a0207b54bbcb494044f1d18d2576da68c

**Comment by Deadshot24359** [comment]
00x16b6121bbe30fd9c7a5a7dae0d9905fa4b54f333b5080b971c3956b30c5e1c74

**Comment by Namrata025** [comment]
0x2241f013dd33c9b651ef890379d757844097bd864a990968ce377111f4cd244d

**Comment by Valony48** [comment]
0x2acf7497541a9f6495599e07d427b9fdba745fb310f0fd16359705a9c2151168

**Comment by Fortunema** [comment]
0x2f8cae06cbf3a754342095b2175d4a3e75de21d1ac85989afc2aaee3bcaedf9a

**Comment by dash4397** [comment]
0x0df054e1dcea3862a63e6d2dd56f60d8cb2020a468d26067628b02562c81b1a7

**Comment by Delma1** [comment]
0x221207dea58a161f65e7e3218cc45eb85e020ab5b10800bd9bf719e6f5e5b125

**Comment by atikaaa3211** [comment]
0x101e343b42b8b770d735756ffa99dc3e610c6f7516871c0942e5fcc50b49da8c

**Comment by Eloemma** [comment]
0x0e4c0611bec47cfbdd61b17845f5e240a2b54c2c133f251a5465609017df22a0
