### ISSUE TITLE
my public key 

### ISSUE THREAD

**Issue by jacob755** [element-fi/elf-council-frontend#1039]
publick key

0x0346fe18efdbcf94ac56da1d8ba4dec008fcf1b4a520bcd7f9e2567aa17e024b
#384

**Comment by Thetobin293** [comment]
0x1af178ed0f50e942f8f74a9b0adac275868c3153781722600a0e6b06aa3e067d

**Comment by JanRuettinger** [comment]
0x3c1e75b9039945C4f6e252b2Af35C0e024E4a93b

**Comment by heivenn** [comment]
0x0f9d54ddd049f9d661649bb466babfc9c210a1547dd4fe93ce4d340b30bec34e

**Comment by onlineincomee** [comment]
0x185d06ce6f0d9c3e61dba25deba47c6224a2c1127c1e2ba4ecb36c922ff11422

**Comment by Asgar11** [comment]
0x28acdc103d5812316aef30429a616559fd8a1bf6ec936baed2ca515d1ad03d4f

**Comment by Eloemma** [comment]
0x0e4c0611bec47cfbdd61b17845f5e240a2b54c2c133f251a5465609017df22a0

**Comment by mhyxz** [comment]
0x067201e65ff151ae5d50605a197e8adc1e12626742c1d8be83b4c6a1cd558777

**Comment by Delivinglegend** [comment]
0x0a8972efe1c43a6a58b7503dfd4d01ecae306731aa6c99e91f8984620adf633e
