### ISSUE TITLE
Github public ID

### ISSUE THREAD

**Issue by Aldrinph2** [element-fi/elf-council-frontend#1043]
0x0f70024bcdc5980c86c290280df4acc06a6c142bce087f9c9a8e82c0c7026597

**Comment by imanitadhimal** [comment]
0x14a0b536177fa548a44a0ef0fdbebfe753f367c760dad38fc5e0033542383b75

**Comment by JISOOO1111** [comment]
0x17e14344e40A28D57E86C7072e7434d4502Ab7fE
