### ISSUE TITLE
0x0f283a239238f51d39cdab42c7d655cafdc21311556083bd6d772e9004312039

### ISSUE THREAD

**Issue by evarich** [element-fi/elf-council-frontend#1045]
0x2f9d7065b7d448ff72e564c762bde9e04a985d82acd2c9f104f79caa05aa36bc

_Originally posted by @siladu in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1085140236_

**Comment by sandeshsegu** [comment]
0x15fe6f8e815c625088b1229d0adb73f2930b321866d2225290f638bb0d7323f8

**Comment by Bhie14** [comment]
0xf3c711aac1e76f16fab230d4ab2c1f06d6e62402b7c6b9743478f274fd5d48b0

**Comment by Eloemma** [comment]
0x0e4c0611bec47cfbdd61b17845f5e240a2b54c2c133f251a5465609017df22a0

**Comment by Delivinglegend** [comment]
0x0a8972efe1c43a6a58b7503dfd4d01ecae306731aa6c99e91f8984620adf633e
