### ISSUE TITLE
AIRDROP 

### ISSUE THREAD

**Issue by ag852002** [element-fi/elf-council-frontend#680]
0x0c91b3cbdace16c14c31c24963106fad8584b16838ab47bbccc40be6c2e85469

**Comment by penggunalayanan** [comment]
0x05290757b2b7030b24d18212807d55c40e0f95b495773469415a2673c387f76e

**Comment by ultimea777** [comment]
0x04868426c3b91b487c5eef7f09611b1d95e1f17777a564cc92a36bd71fadf924
