### ISSUE TITLE
0x1be8092f44161e967c777932d693c733af19f844ee2069cc5904b2e1e0326403

### ISSUE THREAD

**Issue by mhmdyvsvf** [element-fi/elf-council-frontend#697]
0x1be8092f44161e967c777932d693c733af19f844ee2069cc5904b2e1e0326403

_Originally posted by @mhmdyvsvf in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1094171458_

**Comment by mhmdyvsvf** [comment]
0x1be8092f44161e967c777932d693c733af19f844ee2069cc5904b2e1e0326403

**Comment by Hoangkha94** [comment]
0x1417cbcd2dd402b6f99a319576d46f6a07d30e28a9b01cad50532c83d646abbc

**Comment by Mujayy** [comment]
0x21e2826c037b034dcc34cff2753c481eb4bf6d3e9d5a8fd6c904d70f14e61dee

**Comment by arkansendy** [comment]
0x20beea5656f0312a46301ec31c0797ba3e805364fd8e014758b71cf5c272dda5

**Comment by tommypatrick18** [comment]
0x025c3005811cca16284913155208fd67db144267568e7cbcaf7bb9d63770004d

**Comment by Rajirox** [comment]
0x27fb2ee691d0cd9da10c014cb02c6fc8f7c170fcb681190d997eea7e516b8377

**Comment by OzN-lab** [comment]
0x00282c80a04bd795dab7cac17107ed72fff61178dcdc41bed597c1ab047aca82

**Comment by OzN-lab** [comment]
0x00282c80a04bd795dab7cac17107ed72fff61178dcdc41bed597c1ab047aca82
