### ISSUE TITLE
Github public ID

### ISSUE THREAD

**Issue by Syahrulaldi23** [element-fi/elf-council-frontend#698]
0x18f5ba5e4a3484eb10d5de6038c990e134344ffd808f743b93e124e18c4aea68

**Comment by nabila12667** [comment]
0x4Bc7039B0BBAe420e649683dFF7492E41EE61E07

**Comment by anno41** [comment]
0x1690794570d79a04454900120fb9f5906226f52dbaf340d32dff461422af9ca0
