### ISSUE TITLE
github public id

### ISSUE THREAD

**Issue by Albertard** [element-fi/elf-council-frontend#699]
0x0759a8e42a2b8c3bfdb2509a7ef39e0c237de8c4d148e3028ac0cc8a17877a53

**Comment by anno41** [comment]
0x1690794570d79a04454900120fb9f5906226f52dbaf340d32dff461422af9ca0

**Comment by Anv1109** [comment]
0x1855c70c92193b133e196c515485cb3affbc4332f33c2b5a623b5e21f9d5dcf4
