### ISSUE TITLE
0x1f6cf026a058c4e18c156c4d98822fe9b2981d77c5ccc12a876a2160df9c62b2

### ISSUE THREAD

**Issue by AleCrypto2** [element-fi/elf-council-frontend#709]
0x2facbb2a4a67f01baa16ea3109722332e57d9d7c7e166e936649d3f468f11cbe

_Originally posted by @KazamiAzuki1 in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1094171458_

**Comment by Merrynz** [comment]
0x244d38b864e7cf51a4c20d433f16eb51def97c693a79c3899743d725e611d42b

**Comment by Agungxvr** [comment]
0x21117c6c4466b45c05c4596bc520b133c95e7906df8926112a0603ae8cc24d62

**Comment by harisyahot1** [comment]
0x11d8c44c5e8d8b06663c1ceda67e7321ee78c68d7ed51f80a73361674266ddcc

**Comment by Dracays142** [comment]
0x303076764561ecd4ea6dc9f38065c92e0472eafa115b41f22584b1b4200a1bbc

**Comment by Ayula96** [comment]
0x029f79e9ddcf4f6c17c931b48ca146d3c40a373256258f13d80f5671a4f07e67
