### ISSUE TITLE
0x0561a11e38633e7e1da2c79ffdb250e69cf6845b7e2496bf945ffc5b69378803> Paste your Public ID in a comment below to associate it with your GitHub ID. Public IDs will be collected until **April 11, 2022**, after which we'll provide a new link to check if your GitHub ID was eligible using your key and secret. Keep them private and don't lose them! The new link will be shared here, on [Twitter](https://twitter.com/element_fi), and in our [Discord server](https://element.fi/discord).

### ISSUE THREAD

**Issue by Nadia463** [element-fi/elf-council-frontend#710]
> Paste your Public ID in a comment below to associate it with your GitHub ID. Public IDs will be collected until **April 11, 2022**, after which we'll provide a new link to check if your GitHub ID was eligible using your key and secret. Keep them private and don't lose them! The new link will be shared here, on [Twitter](https://twitter.com/element_fi), and in our [Discord server](https://element.fi/discord).

0x0d6d5ccad8d5c59344bd8aa6466f3b659c7f4488332ff4eafaf1ff349cfb845d

_Originally posted by @Thanhle1067 in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1094171237_

**Comment by Uyuna12** [comment]
0x134e18127be06283faeb3df7fc533f3ba2e15332b4fd022e21c1f0324a2dea45

**Comment by rapwindsoul** [comment]
0x2976545f881d1cd5c43a21a2a220674d4a1739619c1f437026a38f13ccc52f57

**Comment by smtamim66** [comment]
0x273a420c85576e28b5c192d90093b4cf5904a54067372a9afdc187d088fa68d5
