### ISSUE TITLE
0x0fc69b05bd377cbaf2ae456661cc3ec88f2c86d6b3a60e5327399d00697bfaca

### ISSUE THREAD

**Issue by Nasmang** [element-fi/elf-council-frontend#714]
0x065d9f14ddf408545b9cc8996f6d749720b3f2bfb334f7f8f29b6232b28717b4

_Originally posted by @ajsutton in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1085140340_

**Comment by antenkme** [comment]
0x161c9d0282e83db6b342260b78116d3235f500fd85e68d990aefc778f7345a6a

**Comment by edolngt** [comment]
0x15f0a2979ba37b1ff6a16835d8d89f81c13763602e10e0f07523a76b68ce18a7

**Comment by DxNishan** [comment]
0x16631a0db569857a8e2dc89e5af5c7fc31ae99dff712b67762b2e50ad12412d4

**Comment by MackoSimo0** [comment]
0x0a8f57afdd70d655dd6852a8282912a209c06b42d4f308aef5845e4982d515c6

**Comment by edolngt** [comment]
0x15f0a2979ba37b1ff6a16835d8d89f81c13763602e10e0f07523a76b68ce18a7
