### ISSUE TITLE
0x0fc69b05bd377cbaf2ae456661cc3ec88f2c86d6b3a60e5327399d00697bfaca

### ISSUE THREAD

**Issue by Nasmang** [element-fi/elf-council-frontend#717]
0x2f9d7065b7d448ff72e564c762bde9e04a985d82acd2c9f104f79caa05aa36bc

_Originally posted by @siladu in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1085140236_

**Comment by OzN-lab** [comment]
0x00282c80a04bd795dab7cac17107ed72fff61178dcdc41bed597c1ab047aca82

**Comment by trickymack** [comment]
0x0ef876793a3f6cf9bb59b723ba75e9faf140c4fdffac4d90f15b9bcf0eaa0c05
