### ISSUE TITLE
airdrop

### ISSUE THREAD

**Issue by ibrahm234** [element-fi/elf-council-frontend#726]
0x83ad518cb7d42a887f6a2eb38a1afbcef1455c376d1fb2d1e2ca61aaafa6302a

**Comment by Wibowoherdi19** [comment]
0x28608f2b04ff01334b7696fddda4908942e8a9006c719f9c29c251bc7afd478d

**Comment by Alhamdulillah1** [comment]
0x0f8d0d11b257835785b407f969ac711c88635a16f8c0b6a49b7a1e9a3e441df6
