### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by Ediwijaya12** [element-fi/elf-council-frontend#748]
0x1a8f96b834f3c1cbe0bd894333f067d1cfa6523cf49a1ed3ebbda49b6d7aad90

**Comment by Ediwijaya12** [comment]
0x1a8f96b834f3c1cbe0bd894333f067d1cfa6523cf49a1ed3ebbda49b6d7aad90

**Comment by ultimea777** [comment]
0x04868426c3b91b487c5eef7f09611b1d95e1f17777a564cc92a36bd71fadf924
