### ISSUE TITLE
Github airdrop

### ISSUE THREAD

**Issue by sandeepmaity** [element-fi/elf-council-frontend#778]
0x1ac6b705a2a5cbbb44596f9eb07fac7d89213c93102c8f0e7d0a5654cb80cd46

**Comment by s1kabayan** [comment]
0x106a6c8fa4d94bc2930ee33dcafe58e3f02333c1845fa5be2879daa3ad2457af

**Comment by Nugdw** [comment]
0x097a12f2a369f9df092fb0a7425ae75d1ba5714665b2e5fb94639f081d26d535
