### ISSUE TITLE
https://github.com/element-fi/elf-council-frontend/issues/384

### ISSUE THREAD

**Issue by Phayvour1** [element-fi/elf-council-frontend#844]
https://github.com/element-fi/elf-council-frontend/issues/0x0c40fdfbf678b3e6f6452e135483d60dad79e7526180d729142b2fd616dea3b5

_Originally posted by @taotuongh in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1094179473_

**Comment by Phayvour1** [comment]
0x0c40fdfbf678b3e6f6452e135483d60dad79e7526180d729142b2fd616dea3b5

**Comment by fazabintang** [comment]
0x2825c96b7bfc99e55b58a99e35f02db86e6e187e761a9746de07df825d195d80

**Comment by nomirizky55** [comment]
0x113df0226de264968141a3c38be52c1006bf8b432df9dd2fdc913f84a8eec4ed

**Comment by Vkb69** [comment]
0x25d54ac91e0464bacbfe0816a9006b28fb79dfbf6887c6227249f963662842ab

**Comment by alamin975** [comment]
0x2700eabdcddde28d3b5a6135b618b6181e8d008402915366a061a6024bbb6fe4

**Comment by Actionking27** [comment]
0x0756ecc68d4a6187949bab94f56a77482c8399226608a9fe4441531dd165e7c0

**Comment by SanAndr3** [comment]
0x20344e0305d584a55e51a9e1d4dc678d1fc67d0fbec0cc6f4e8c5628e08d21f8

**Comment by kirigayakun170** [comment]
0x2f4317ee6b1ed[224562](tel:224562)d[90303645](tel:90303645)e4d87dd72eed963b659f325c85ddc6bce792

**Comment by cryptotyga** [comment]
0x18a37f91cacd9ab2cbd089456519f199a5e116a12b69a5fae8ca9ac18e73eb3b

**Comment by Nadiashaki** [comment]
0x0f8c36ffd8410fe8cb1f9e668410303ea5373284e825ce32b6d5159d1c543673

**Comment by Nirav0910** [comment]
0x3051dd2f67048e312427d00c65b509a034ac44dbd1b41f0456582e1a60cd83d6

**Comment by Sangram6370** [comment]
0x1815ab00577362c74f16c07c552341007d5039079083cc1629e4c5a4ae581ae6

**Comment by Nirav0910** [comment]
0x3051dd2f67048e312427d00c65b509a034ac44dbd1b41f0456582e1a60cd83d6

**Comment by tata7772** [comment]
0x164d681a403c1cf1c5de2ec257f988d131950db61e060b3d2880253de6cd8d49

**Comment by Ucheiyke** [comment]
0x01cd30faffbb1f74c8b7a6671635837f6332e0bb4a0ce15353fd0508cdd5d0f5

**Comment by Adnan-crypto** [comment]
0x15ee3c135b28ed90e094f83b128f250022e06d062314a051a90d4d69c22daaee

**Comment by Adnan-crypto** [comment]
0x15ee3c135b28ed90e094f83b128f250022e06d062314a051a90d4d69c22daaee

**Comment by simaoatb** [comment]
0x0db1322921f0e422b0c8c10243eb59870fb87c6c576f585824f6a543e148d59b

**Comment by Alicomm** [comment]
0x20712a78431ca01b6cd6adf685095e7a4b8ee3e8a44ff08f7c4d681b89ad4058

**Comment by realsedrick** [comment]
0x19354b959438218b8df5b73b09738a400996b40f5758b2c1cd9b8bbb49e22846

**Comment by wilsonchilboy** [comment]
0x27d787922afc027138ee49dcc96899bd62924d65650708db0a9d525890cf3970

**Comment by Fortune022** [comment]
0x2e8b3d38e1eaf7037b8275fd2cd60467d27fd8ea69626c5722bcaa08dbc2654c

**Comment by BoyCope** [comment]
0x147e5840d3c9945a29fcef6e721a1095adc21f29892dd6905ccaa31e1708ca06

**Comment by Charlesz-charles** [comment]
0x1e09a8f9787c26474ed398b08de6c439a80eab8f4055864e8b5bfb30260151f1

**Comment by Domohare** [comment]
0x296d6289b93ad627f4fb0be83e9a7b9240eb2c4e673d22023009b5311fb0adb4

**Comment by Hanasta** [comment]
0x0ccf17233da6a4af2f1de63625c78e29c0f9a60a8d0a4619bbd8a2f0b840afc4

**Comment by sophisticated20** [comment]
0x2e69e5fceab7d163bd77e4a2d374d15712be9f4aad4f682ed65b1b9e4c464e27

**Comment by oneawal** [comment]
0x064ce54d81368e14eed0756d45af4dbc28613c4adc9cb3e41c2d1999eb822923

**Comment by clurut11** [comment]
0x2bd54085547146899b1e268d1a67c1fe32e811b300b73ea5b71c9872fbfd85e5
