### ISSUE TITLE
0x038a1ced868ed6ad04175047e7f71b007b578fd6b4dd54d1ca46a812899fa142

### ISSUE THREAD

**Issue by gepenkid** [element-fi/elf-council-frontend#876]
0x038a1ced868ed6ad04175047e7f71b007b578fd6b4dd54d1ca46a812899fa142

_Originally posted by @gepenkid in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1094178925_

**Comment by BoyCope** [comment]
0x147e5840d3c9945a29fcef6e721a1095adc21f29892dd6905ccaa31e1708ca06

**Comment by Kvngabdul** [comment]
0x1a046e1574b3122c716a4b6795c28a4da125658ae1ae200e38f61a506c9d6cbe

**Comment by Ogunbright** [comment]
0x1fcec540c728549c277b9cb78a252f3df740f3fb47a45ab566eb82a4b3f7a500

**Comment by Jide953** [comment]
0x126efc69598fce684c856fbaf0c1139ca1c0557c205322460e104abd72df9089

**Comment by sophisticated20** [comment]
0x2e69e5fceab7d163bd77e4a2d374d15712be9f4aad4f682ed65b1b9e4c464e27
