### ISSUE TITLE
> Paste your Public ID in a comment below to associate it with your GitHub ID. Public IDs will be collected until **April 11, 2022**, after which we'll provide a new link to check if your GitHub ID was eligible using your key and secret. Keep them private and don't lose them! The new link will be shared here, on [Twitter](https://twitter.com/element_fi), and in our [Discord server](https://element.fi/discord).

### ISSUE THREAD

**Issue by bosunvee** [element-fi/elf-council-frontend#951]
> Paste your Public ID in a comment below to associate it with your GitHub ID. Public IDs will be collected until **April 11, 2022**, after which we'll provide a new link to check if your GitHub ID was eligible using your key and secret. Keep them private and don't lose them! The new link will be shared here, on [Twitter](https://twitter.com/element_fi), and in our [Discord server](https://element.fi/discord).
> 
> **Ineligible submissions will be deleted. Beware bots! 🤖**

0xD183AF58B656b6E00D1F5f78d914bf80Ac87410D

_Originally posted by @bosunvee in https://github.com/element-fi/elf-council-frontend/issues/724#issuecomment-1094228462_

**Comment by tarantula1108** [comment]
0x09936191f97f5a443301bcfe0f3004bd2ae97d784bbcdfcf931465c349e954ce

**Comment by damorela** [comment]
0x22ea8c4f0e5ab0dd779f2ebd2248e43971fcf83885bfebaefbe02decb32c63fa

**Comment by yentieu290** [comment]
0x157ce5d061c4c71628825f0d37bd9d813066e10a4b4a2949db1d23a47c5bfe4c

**Comment by chiemnghi** [comment]
0x284c23d41b512c2f357c8174f72d06347f1c9c4acfe20bf03107e18193e6230e

**Comment by ngocninh43** [comment]
0x115834e34b69ad807c1072144220159117ad0c812a9b69c99401c9f9bcf9dce1

**Comment by lesuong27** [comment]
0x2bb3213ebf89c768ab7b148def0d9015090db79d24d36dff93feb73441160e8c

**Comment by lenhi400** [comment]
0x286937ca638da4c8b9bf30e37d20c5f997c9c11bff1526d2bafdb9632efba124

**Comment by cuuan9959** [comment]
0x2b90b2e8138ce1fee2f326ed21a655ba74e5d2bdfa95432052eb3c0de2aa8492

**Comment by nlinh815** [comment]
0x03974097e81f14dc99db90010f75e882bd0c540c5776c27151a9f4ae6975827a

**Comment by linhchiem60** [comment]
0x299393ef270f1afa2f275cff78057779a786e0dbee881858698158710acaa180

**Comment by duongthuy645** [comment]
0x2edce2a8bdd10c8386d48533bb2c2e1ccc64a3dcf135408b4539cbaec62017d0

**Comment by tungdam97** [comment]
0x0abc8783f121903aaf35790f4e7695cc16699275687a3ab0ab0ca4fab4a48927

**Comment by nhungn84** [comment]
0x2e34c0539abcdee01bfc1c246092898e6bbf573e5c4b28ca14fa9bf4a7931053

**Comment by thudao876** [comment]
0x1d6d861f164795060e50ec211fdcfe150ce42fd6b2058d1e16639c9a402c9842

**Comment by phien76** [comment]
0x20a1787bf909831ebb76f327c318772260b098070aa2df00e55c4c026e36d43f

**Comment by trantan663** [comment]
0x14c36984bd9c71db1e334663dac527a5d6b56990293e30cd2e808a2511ab7319

**Comment by trongdat4820** [comment]
0x2e28476f485374c0f30f782929ae5f4bb38d9ccf80b6d72f5b05dc36c421a2b6

**Comment by hanba882709** [comment]
0x2f9ec4daf22785cf790f4ef18a2259e9d207284437349bd206f816396706ee8a

**Comment by nhanho788952** [comment]
0x10e5caf5be9421bd9fbe24ec2369c3368172194e9fbaa65ef02ed181baa43db4

**Comment by hanhdat685237** [comment]
0x17fc0d70fb4a5e2232025dd7ad7437b7f0744a5c41ec84b163e2529d73635faf

**Comment by thienhoang100785** [comment]
0x1988e72eaef2a45871b87e16f2ebcf1f8b247495cb450ebd361fc0a75fa0ad84

**Comment by uyenba216893** [comment]
0x01567560ce2ce095ce8e584df74eb5b3d2ab3706b9eb875cc6ebfbad4fb59fa0

**Comment by thienphuc790** [comment]
0x2437273679554a7d573c562884f4e8a970ecb8a658fa3aa5a89eb922a580258f

**Comment by handung759377** [comment]
0x2fed981628f094e970dd62898c282eb6eb0821e5765a6cdc8b966232c0abd457

**Comment by datbui224294** [comment]
0x11c38764c878dcff7a8d14e9139e10cde85750d85072a7beb124a318c7f0d74f

**Comment by kientruong264923** [comment]
0x2a1d98bfe16d726c2055f2663660c27fe87a2af5d4631ed5c75a546c08159b60

**Comment by suongdao639118** [comment]
0x17a0d241d4da3c904dddf8da8e91b17b3f6be031e3b122360065789680a6ea77

**Comment by nghila854059** [comment]
0x2bd54ae6b3f2d5fdc239f016cc9d5ce344574f8da87d38f85fa4462e7aa28472

**Comment by cuongdao399808** [comment]
0x14690d8d38a195bf75889f07f3bdec46df4e57e0669883cec197411981c553aa

**Comment by duyho983010** [comment]
0x190fc05a48fcd8c699bc33d375d4ccf4bb816cdf91ff5b09862c9eb08c230962

**Comment by thinhla154727** [comment]
0x1440ed152e8585da621e3e8a63f9dd626e18dff0b4828399c4ac54ac601b939b

**Comment by khangphuc75** [comment]
0x195380e0f5e4ffff42c4c31e49a7377f30d1cfaa19513c09735af840753bdfc6

**Comment by cuongha477609** [comment]
0x1a83649cabd4eec5133fef6d94b7301a517a12c4b417f0ade5f59f88647f1cc4

**Comment by vydam269153** [comment]
0x27a5b5582eaa74a9c03f6c2cd8656ec37fb7ff05249e8f35401a1e479ae079c3

**Comment by tamluong899633** [comment]
0x26ed8e2e95cb30c3eddd225c82dab7cdf2ce0a1c2e7f05e4a23f88501a9d8091

**Comment by thuphan927540** [comment]
0x0500dac5e5684e07708529fb2da9922dac50539471289a675300351299cb5ad1

**Comment by vinhchu730898** [comment]
0x27a44e3ef73891eb03adc79e6d72ff4137a4c16dbcbe7ab42529044e424db032

**Comment by maidang793278** [comment]
0x2d7c0055c2a4fbb95c03334d562e51cd3daf7f319c6748f08c33c640d767dcd1

**Comment by thinhcuu935862** [comment]
0x1c60c77148b65dffbe23599df1aabf980e6346e58f0427f96c4af5242fc23c6e

**Comment by anpham962499** [comment]
0x14a86651f01289bae1387dcaf29774e019539581829923dd01a2fef296390462

**Comment by loanphan563728** [comment]
0x09131bcdf067040ce354ed07715fd4f34c8f6d0f8efe6a41bf3e85e4f21a865b

**Comment by yenninh375575** [comment]
0x2d98e10f303945babf63de3e0ccf68cf5c5d9473d1304a9ecae222597e9a189d

**Comment by hala903927** [comment]
0x2a6832356d1fcc4f2fc4c06544af083c75cc66bddb20214905909344ffdb7586

**Comment by dieptruong848565** [comment]
0x1628ed430923f1a8970a67588b41fecc9ff13c5cf69c82c85490ad3c03459255

**Comment by thaochiem284489** [comment]
0x2aa1283c9166eb496813b230577e4742b9699376dcec88672226c61fac42653a

**Comment by khainguyen924646** [comment]
0x062a0ae5cc4857de549145512d6e2bf3b82569245672fd0254ca71741a099fe3

**Comment by thubui589470** [comment]
0x0e0079fb4c1f2d3096e4ff05c42d8473b4419b68a954e82d1334fabeb8b5bfd3

**Comment by khanhluong631280** [comment]
0x1d1fe39fd20709980e7b4ef375e85cd9500bb1db95a46eac870db5bbe2f595b7

**Comment by hoanong205338** [comment]
0x1b9ea76fea7bd33c3cfc7f8015c5d4e26d53627045781815f1b928632d81915d

**Comment by tamvi881167** [comment]
0x1f446c25c0251eb1820c740cdb178c9189ca172f75e28e65fbc248befd944095

**Comment by thitran898474** [comment]
0x1993b592e346eedfcd1d6b09514e3e1641cb471caf2b6aa31fc383168a49c5ff

**Comment by datbui702371** [comment]
0x243fc0fc1f39b52229f806e49bcc3fa56a7fcc95652ccc007b43e519525687f1

**Comment by uyenho490606** [comment]
0x2ef4ea9f45bcdc65b408e5a41662b12de8b85753645f24f0c3f7b17a9fabfd01

**Comment by hanle712718** [comment]
0x247dfa09c80519f9bc024b64b9533374aae0696b407b45976001b85d77e575a6

**Comment by diepbui954241** [comment]
0x07bb8d01689550c39343b71c69547d1fbf8e76325840ea8ea2f5e8f75083872f

**Comment by duongtran956812** [comment]
0x0de0f27d37a3b8399d824d1a1439f69f8ace8d8a89e55edf6a633db7ef000022

**Comment by khangnguyen802316** [comment]
0x15938f5d8ae64244b1ebe9db4ca9ec49a20a83d5c4087d1b9e3178f011d3aaa3

**Comment by minhle213479** [comment]
0x1bfc799e5cf04719f91924aa4973fc7a8623780579ddb096d7ca0973b6ab995e

**Comment by vyle883672** [comment]
0x156a35ab2343de20592f0987ef85efc3b59e9a9e359ec85382c2be29cfbfeb30

**Comment by ngocbao219226** [comment]
0x16ec697598f5d100defe2a5e660214ce46b05a556e2bd0aa64c7f6918d1fc251

**Comment by namla564125** [comment]
0x033bbcc3e5d3cd4223d07c6872a581bd929b5cc9443d8e00538375b038d61b2b

**Comment by phinguyen388712** [comment]
0x1b2eb77dd8fbe7f1b37ffb4a8c2c77992f3fad06b36a58d6db73d9af40606eac

**Comment by nhunghoang932751** [comment]
0x1dc278e6f1bec7e96bb1da942adb4fbf598f95a700a8480d4238dee47f0104f0

**Comment by khoiha215588** [comment]
0x2231cb5baf547d478b1804a0d6077aa61bcda680a5c5e059537cd0f92995a0cf

**Comment by phiduong695172** [comment]
0x2ac7aac269302a0e275a6ec3e252593c4310cd1ad3aae1a14f2f16d642b29860

**Comment by chiha446170** [comment]
0x16cc7d95d6b0dea10ea6f668fc0b5bb41f8ee0e25a548caf210c8fa40a61bb30

**Comment by ngoclieu845719** [comment]
0x081278d4387c2e2e5acd5f4a4f6c7d15b513b17c627d2ba2c2a709a6fd33e640

**Comment by quocphan758436** [comment]
0x031601c5231f1614fa98e6cac2d6b4179e8ee363d0bbfa341b858368c9ea0719

**Comment by khoaduong730191** [comment]
0x0721fd83d11389f821c22f3174acea3c1b435018c786a96f6bcaf457faf2551d

**Comment by phihoang928274** [comment]
0x268acadad253f5a72eacbd7e489712f50bd693a0abcddc405b350eb3c0ab4c47

**Comment by uyly434552** [comment]
0x24b2dd3aacb14190072252196bd083cca86f4ab33d4e214fbafd24a7812d68eb

**Comment by chihoang498495** [comment]
0x276bf60740a06a8252da1ecea5ec08c36728ade0bf49a1cd9921a3d8a2f7d91b

**Comment by vanla428137** [comment]
0x2c37c17f96ba4dffacd01097553f3d6e3d32c2be0ee44d1d481dccb935da98b1

**Comment by nhitran219496** [comment]
0x20511b39b78c2ce6e90b117df11d4dfa2f35061d309993cc8ef3d50be97ed498

**Comment by quangla993063** [comment]
0x07f349f2cce24463b2fa55047ba9b54bb512cac97dd37562053a7a255c8fbc5f

**Comment by nganpham108675** [comment]
0x25df5e91e87e86164494aa210282cc821105864dc48016ca7416a0be422dc6e1

**Comment by lyngoc16** [comment]
0x2127a734de70a1fd92ad6e624e12b1ac6161d75c51ed0a73911215c978b37a3b

**Comment by loandat490258** [comment]
0x0d9c1ee2d1d8c28c71e95bdd5eabd41026904c803626888799cf6e0dca9ba072

**Comment by minhtieu981900** [comment]
0x1e920a1f5050d935f161e1c0bf18ec4ff65e53c1beaf010b413e8012a5d3281b

**Comment by khanhdang396457** [comment]
0x071b909713e68b31ec95bee632678222734fd55a60ada9da578259ae74feab24

**Comment by trungtieu378** [comment]
0x00f3d70760a9d8585ca05ae9cce30f47c17db554ec97dda741fb2652556c7e69

**Comment by doantruong132770** [comment]
0x18cedb714485834eef287a5d000e5cfef0e9ec92d6b7ec829e8ec6b2c1625adb

**Comment by nhidat235554** [comment]
0x28ba315fc65287b140729d221fa407e250e52ebbfdb3c02de81c41b1eaf71da2

**Comment by huyle205345** [comment]
0x28690d6f069a80739ec8125e6802f3da20b6a7e7e575bb6af350c2b9796eb279

**Comment by hanvi844455** [comment]
0x0bd7e338ba83847f79303b4270d7a9d2fbbf1f051ded2e82ab5d7a759f92dba2

**Comment by nhandinh986860** [comment]
0x111785bc3f9077522ca690eef63f42702f008de0ddd6d3ffc334d1d6a6aa5abb

**Comment by nghiduong369339** [comment]
0x2f92b8e0947cffaa78eca07d94b94bce4942eccd21183ab5a1fcebf5decb265b

**Comment by ducbo911765** [comment]
0x3017dd73e75e3b9b059658bca3a095e69818275d814cf7e5437641dc2ea77a5c

**Comment by trangtieu206279** [comment]
0x00dd107d18e9ca70ec81d3554e5b94cf741189eff8550536097cca004dd88675

**Comment by khanhnong922448** [comment]
0x10aba66459cac3df21048fe3de83bfae5a3bee178c795a195cfcecd8c1ceaa93

**Comment by thientran993350** [comment]
0x25c87637df42cfa40aa62bed30da8ab6cf27dc29bd9d59eb5b34378d370e0088

**Comment by chicao179641** [comment]
0x014dbe732a877fa78893517b71094765d8caa3d090fcc0b8db46e369a44a0c6d

**Comment by ducchau264150** [comment]
0x17e58f298f5b20ca0f93aeb2db115f0ac867873fb856589f1d230a05621499ef

**Comment by baobo318842** [comment]
0x036f12719d12d43afd4363d8114115f930afb5068d368b14b7638ca3ead79a1a

**Comment by minhtran249150** [comment]
0x273aa0f23f019348714632ea1fd1e033be51640a4709d271e9430176b82adc3c

**Comment by chivi150488** [comment]
0x179ef2cbf356d43612b4cdea83d7da06f7345baae5049a360fa8ac6ca828c7be

**Comment by thudung975243** [comment]
0x2c043827b7deaeb80c1dabfde157d261af0fee259c892b74d0d7c7ba240f94d0

**Comment by nhile539465** [comment]
0x19bd622a3906269a31957c6f8eeba30c960592414017be4e4a9b6f178071906e

**Comment by thuydung848222** [comment]
0x1e284ffdab769d83192f146b8e209f1b8941e8642d17389cd411644fdeb47af3

**Comment by thiho674101** [comment]
0x1dd27da0e4b578cd9e7e00bac632cde1ef0b5ec27d01a1cba410450af0490d34

**Comment by maroofahmad81** [comment]
0x1efe9b56274b43fe466df647659c08b02d3751c523401cd27e2595a1d2b55659

**Comment by vytruong955161** [comment]
0x083948b236103317837d066a1452616abe7ee72c78483bec63b45410344b43e8

**Comment by minhla488723** [comment]
0x2053f411321f784b6e6c57c4ed09c282f640f54f3c36fe2e6da70c86ea77dd48

**Comment by xuanche527701** [comment]
0x06941946da2a6fd7e24edc04b692c7d48cb5ae6df595a17c0e3714cc01450f68

**Comment by quynhphan817927** [comment]
0x114bc8d116cf9d09e9d1a8e90ec3d9bfd88b847abdb958ce020f8e539f7eb16e

**Comment by khoinong810122** [comment]
0x152d89bd4fb2f2945b68ff30c98e9c04bb48f5b404e9d569a84c389088817400

**Comment by dungtran695192** [comment]
0x1e9e79d7663f9a1b5ed2c0a06ba7729d7c3764a88d3ac1b9f2068756a9c7a245

**Comment by dungduong343748** [comment]
0x0e2fea79340c1076cb924c89807009ef10b72db94b9e346a15df4118c847df12

**Comment by thicao443205** [comment]
0x1c9191ec9241d39e23861f0e960a3e7fff3448c5afc017f62c87e74136844379

**Comment by hanhha919200** [comment]
0x0dc0284bc98d0d7480e00a2cd7d0eeba067139d1c2792835365cd2933ec0b641

**Comment by thuybui846345** [comment]
0x0cf1a3fdfd7de02173f8dcf96d86e355df762479bdd8a5cf0c7a45bda2d1d5d7

**Comment by anhla796294** [comment]
0x2a55ebb7bb683114bf098adbed2e6082480958f7b049a94b4fb958cf9a52d740

**Comment by nhuvi975963** [comment]
0x24c677ddf4c0b9e525ed417dcf8b1ee18dd5b1836b52f26559ddf22b186a51f8

**Comment by giahoang398185** [comment]
0x16a175a6049ce5529ee7068c7848805b76c11163b2361c782de736a08ac3f3ca

**Comment by duongcuu329366** [comment]
0x08d796d58a4292b584afc4ff1752c53e5a4e7a040d4e591261b9f7beb1774d74

**Comment by khoila568313** [comment]
0x29665ee4e8f6c2495c4c09f240bf584bf7fc2f55746bab69242032b99581a7de

**Comment by khoale115436** [comment]
0x18d3f19f27d226434d376cc1152e7dfca00d945cf043dd6fe695cecc9937bf8b

**Comment by khangchu468264** [comment]
0x1320ec4653a04def631b5ef9e025acebdfd8adef7dcc4e5c92e561650d683fdf

**Comment by tampham467390** [comment]
0x16b04eeaead372bc684f98fd3e04e45d4f58093f1ce68c5a726428016eb81339

**Comment by ngocninh249743** [comment]
0x0728b59020978d1e8561485a6d13c17446aba5b352a871c1f171795a1a9bec27

**Comment by lanla180090** [comment]
0x1468b048f58ea1d6f4916fa0806f450cd0bdf6090b8f7b7cb5de2332b73e5cc2

**Comment by khoidinh924015** [comment]
0x25767183057ca16c3c163d3b442a1694c6319ed71f7ca35faab790dc7a383b73

**Comment by minhninh452687** [comment]
0x0bc36c0aff1a3d3e6f5f15bc23b7f0ca9a457317afa0d96ca8522936ef991aa0
