### ISSUE TITLE
0x061f976c60425822985683f10dec3c1256dc71409c4661e276b68bce51817e45

### ISSUE THREAD

**Issue by JOHN52903** [element-fi/elf-council-frontend#979]
0x061f976c60425822985683f10dec3c1256dc71409c4661e276b68bce51817e45

_Originally posted by @siladu in https://github.com/element-fi/elf-council-frontend/issues/384#issuecomment-1085140236_

**Comment by JOHN52903** [comment]
0x061f976c60425822985683f10dec3c1256dc71409c4661e276b68bce51817e45

**Comment by EXEL24** [comment]
0x08faa627a51514d7cb1a62c55ec37102d97c8ad9dd00a30d1265721a40e24e7c

**Comment by HaruHaru2** [comment]
0x26fb2c0a6c8c0f6370f36a3d2265b2f8d5e24486751e2ee4e76da067b1f70649

**Comment by Ebencarl** [comment]
0x953a5F597Ce881Ea487403775410aaEf53dDF032
