### ISSUE TITLE
0x0332144bd77674313b14c3d93ba77a150d486c9fca67482ee927a1927b7f358d

### ISSUE THREAD

**Issue by khoer17** [element-fi/elf-council-frontend#988]
0x1b4babd26f32d6f6950bb64aa988519267efef10dd7207105c0d3c431a775564

_Originally posted by @dadargulungpedas in https://github.com/element-fi/elf-council-frontend/issues/722#issuecomment-1094262307_

**Comment by khoer17** [comment]
0x0332144bd77674313b14c3d93ba77a150d486c9fca67482ee927a1927b7f358d

**Comment by StasKlimanov93** [comment]
0x265b060b84f15f8211b5f504af5459d5abb3698aa41803b5d6064b3480ecf44a

**Comment by johen089** [comment]
0x83Cf937f314B67f44c0E7E57D960426EDAd396eD

**Comment by bolong89** [comment]
0x114021b8397cdf758e6514a431dff0661b5715a5df989a694ccb35bf8b18c271
