### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by Aulia235829** [element-fi/elf-council-frontend#998]
0x2b7eb9a9aae5a25e0a1ee8033599a40ffafdc586c23c2764a9b12d99fbb426a3

**Comment by ethluzi** [comment]
0x024696ebb37723929e8f12e008d7f16b6d710563b66ab7cff22d75452f1bf45b

**Comment by Korageous** [comment]
0x2e80ae6b5147eabd7fcd64ec1a2438fa87533f8c3b7d3492a507c7be62e52b98

**Comment by Fabunmiegbe** [comment]
0x27db6595d8af7f2a43b13dd9a9fa1e4f8d73ed88ac06e7cce69c0f0a0b27c537

**Comment by FABULOUSPIO** [comment]
0x1d1a7c61bf0a75bb249a9957ece43b5094434daa8f5af25d9b22234b4669e580
